// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using SupplierRatingPredictionML.Model;

namespace SupplierRatingPredictionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            //ModelBuilder.CreateModel();
            Q_ModelBuilder.CreateModel();
            C_ModelBuilder.CreateModel();
            D_ModelBuilder.CreateModel();
            // Create single instance of sample data from first line of dataset for model input
            //ModelInput sampleData = new ModelInput();
            //sampleData.Commodity = 2;
            //sampleData.Supplier = 6;
            //sampleData.Manufacturing_Process = 3;
            //sampleData.Volume = 17300;
            //var predictionResult = ConsumeModel.Predict(sampleData);
            //float predicted = predictionResult.Score;
        }
    }
}
