// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using SupplierRatingPredictionML.Model;

namespace SupplierRatingPredictionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput();
            sampleData.Commodity = 1;
            sampleData.Supplier = 4;
            sampleData.Manufacturing_Process = 1;
            sampleData.Volume = 12345;
            var predictionResult = ConsumeModel.Predict(sampleData);
            float predicted = predictionResult.Score;
        }
    }
}
